spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://user-service:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/users/**

spring.cloud.gateway.server.webflux.routes[1].id=job-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://job-service:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/jobs/**

spring.cloud.gateway.server.webflux.routes[2].id=application-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://application-service:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/applications/**

spring.cloud.gateway.server.webflux.routes[3].id=shift-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://shift-service:8084
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/shifts/**

spring.cloud.gateway.server.webflux.routes[4].id=attendance-service
spring.cloud.gateway.server.webflux.routes[4].uri=http://attendance-service:8085
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/attendance/**

spring.cloud.gateway.server.webflux.routes[5].id=payroll-service
spring.cloud.gateway.server.webflux.routes[5].uri=http://payroll-service:8086
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/payroll/**