spring.application.name=campus-workforce-management

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/campus_workforce_management
spring.datasource.username=root
spring.datasource.password=arjun8919

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true