spring.application.name=analytics-service
server.port=8095

jwt.secret=404E635266546A576E5A7234753778214125442A472D4B6150645367566B59

job-service.url=http://job-service:8082
application-service.url=http://application-service:8083
attendance-service.url=http://attendance-service:8085
payroll-service.url=http://payroll-service:8086